board_settings:
  fqbn: esp32:esp32:esp32s3
  port: /dev/esp32
  sketch: epj-neck
  baudrate: 115200

arduino_cli_path: None
servo_settings:
    1:
        home_position: 0
        limits:
          min: 0
          max: 180
    2:
        home_position: 0
        limits:
          min: 0
          max: 180
    3:
        home_position: 0
        limits:
          min: 0
          max: 180
