board_settings:
  fqbn: esp32:esp32:esp32  # ESP32 normal
  port: /dev/esp32
  sketch: epj-neck
  baudrate: 115200

arduino_cli_path: None

servo_settings:
  1:
    type: continuous
    degrees_per_second: 500
    stop_vel: 94
    init_vel: 95
    min_pwm: 0
    max_pwm: 180
  2:
    type: continuous
    degrees_per_second: 500
    stop_vel: 93
    init_vel: 95
    min_pwm: 0
    max_pwm: 180
  3:
    type: continuous
    degrees_per_second: 500
    stop_vel: 93
    init_vel: 95
    min_pwm: 0
    max_pwm: 180
