board_settings:
  fqbn: esp32:esp32:esp32  # ESP32 normal
  port: /dev/esp32
  sketch: epj-neck
  baudrate: 115200

arduino_cli_path: None

servo_settings:
  1:
    type: continuous
    default_power: 95
    home_position: 95
    limits:
      min: 0
      max: 360
  2:
    type: continuous
    home_position: 95
    default_power: 95
    limits:
      min: 0
      max: 360
  3:
    type: continuous
    default_power: 95
    home_position: 95
    limits:
      min: 0
      max: 360
